In [1]:
import os
import pandas as pd
import numpy as np
import requests
import json

import matplotlib.pyplot as plt
import scipy.stats as sts

from api_keys_am import premium_api

In [2]:
list_url = "https://pkgstore.datahub.io/core/s-and-p-500-companies/constituents_json/data/8fd832966a715a70cb9cf3f723498e3b/constituents_json.json"
base_url = "https://financialmodelingprep.com/api/v3/"

In [3]:
response = requests.get(list_url).json()
#print(json.dumps(response, indent=4, sort_keys=True))

In [4]:
df = pd.read_json(list_url)
df.head()

                  Name       Sector Symbol
0           3M Company  Industrials    MMM
1      A.O. Smith Corp  Industrials    AOS
2  Abbott Laboratories  Health Care    ABT
3          AbbVie Inc.  Health Care   ABBV
4          ABIOMED Inc  Health Care   ABMD

In [5]:
df['Q1 Rev Growth'] = pd.Series(index=df.index, dtype=float)
df['Q1 Rev Growth'] = ""
df['Q1 Op Inc Growth'] = pd.Series(index=df.index, dtype=float)
df['Q1 Op Inc Growth'] = ""
df['Q1 EPS Growth'] = pd.Series(index=df.index, dtype=float)
df['Q1 EPS Growth'] = ""

df['Q2 Rev Growth'] = pd.Series(index=df.index, dtype=float)
df['Q2 Rev Growth'] = ""
df['Q2 Op Inc Growth'] = pd.Series(index=df.index, dtype=float)
df['Q2 Op Inc Growth'] = ""
df['Q2 EPS Growth'] = pd.Series(index=df.index, dtype=float)
df['Q2 EPS Growth'] = ""

df['Q3 Rev Growth'] = pd.Series(index=df.index, dtype=float)
df['Q3 Rev Growth'] = ""
df['Q3 Op Inc Growth'] = pd.Series(index=df.index, dtype=float)
df['Q3 Op Inc Growth'] = ""
df['Q3 EPS Growth'] = pd.Series(index=df.index, dtype=float)
df['Q3 EPS Growth'] = ""

df.head()

,Name,Sector,Symbol,Q1 Rev Growth,Q1 Op Inc Growth,Q1 EPS Growth,Q2 Rev Growth,Q2 Op Inc Growth,Q2 EPS Growth,Q3 Rev Growth,Q3 Op Inc Growth,Q3 EPS Growth
0,3M Company,Industrials,MMM,,,,,,,,,
1,A.O. Smith Corp,Industrials,AOS,,,,,,,,,
2,Abbott Laboratories,Health Care,ABT,,,,,,,,,
3,AbbVie Inc.,Health Care,ABBV,,,,,,,,,
4,ABIOMED Inc,Health Care,ABMD,,,,,,,,,

In [ ]:
for index, row in df.iterrows():
    ticker = row['Symbol']
    growth_data_url = f"{base_url}financial-growth/{ticker}?period=quarter&limit=3&apikey={premium_api}"
    response = requests.get(growth_data_url).json()
    
    try:
        df.loc[index, 'Q1 Rev Growth'] = response[2]["revenueGrowth"]
        df.loc[index, 'Q2 Rev Growth'] = response[1]["revenueGrowth"]
        df.loc[index, 'Q3 Rev Growth'] = response[0]["revenueGrowth"]
        
        df.loc[index, 'Q1 Op Inc Growth'] = response[2]["operatingIncomeGrowth"]
        df.loc[index, 'Q2 Op Inc Growth'] = response[1]["operatingIncomeGrowth"]
        df.loc[index, 'Q3 Op Inc Growth'] = response[0]["operatingIncomeGrowth"]
        
        df.loc[index, 'Q1 EPS Growth'] = response[2]["epsgrowth"]
        df.loc[index, 'Q2 EPS Growth'] = response[1]["epsgrowth"]
        df.loc[index, 'Q3 EPS Growth'] = response[0]["epsgrowth"]
    
    except:
        print("Missing Data...")

Missing Data...
Missing Data...

In [ ]:
df.head()

In [ ]:
df.to_csv("../output/growth_data_SnP.csv")